### ISSUE TITLE
Errors while inserting iCubGazeboV2_5 in Gazebo

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-model-generator#90] opened 2018-05-17 16:02 UTC
My laptop configuration is:

- `yarp`, `icub-main`, `GazeboYarpPlugins`, in `devel` branch.

- Gazebo version v9.0.

As soon as I inserted the `iCubGazeboV2_5` model in Gazebo, on the Gazebo terminal an endless list of errors appeared and Gazebo crashed. Here is the error:

``` cmake
[ERROR]CBW( /icubSim/left_arm ):  getMotorEncoderAccelerations  on device left_arm_no_hand returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_leg ):  getMotorEncoders  on device right_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_arm ):  getMotorEncoders  on device left_arm_no_hand returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_arm ):  getMotorEncoders  on device right_arm_no_hand returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_arm ):  getMotorEncoderSpeeds  on device right_arm_no_hand returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_arm ):  getMotorEncoderAccelerations  on device right_arm_no_hand returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_leg ):  getMotorEncoders  on device left_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_leg ):  getMotorEncoderSpeeds  on device left_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_leg ):  getMotorEncoderAccelerations  on device left_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_arm ):  getMotorEncoderSpeeds  on device left_arm_no_hand returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_leg ):  getMotorEncoderSpeeds  on device right_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_arm ):  getMotorEncoderAccelerations  on device left_arm_no_hand returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_leg ):  getMotorEncoderAccelerations  on device right_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_leg ):  getMotorEncoders  on device right_leg returns  true or interface not availables [ERROR]CBW( /icubSim/left_leg ):  getMotorEncoders  on device left_leg returns  true or interface not availables 

[ERROR]CBW( /icubSim/left_leg ):  getMotorEncoderSpeeds  on device left_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_leg ):  getMotorEncoderSpeeds  on device right_leg returns  true or interface not availables [ERROR]CBW( /icubSim/left_leg ):  getMotorEncoderAccelerations  on device left_leg returns  true or interface not availables 
[ERROR
][ERRORCBW( /icubSim/right_arm ):  getMotorEncoders  on device right_arm_no_hand returns  true or interface not availables 
]CBW( /icubSim/right_leg ):  getMotorEncoderAccelerations  on device right_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_arm ):  getMotorEncoderSpeeds  on device right_arm_no_hand returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_arm ):  getMotorEncoderAccelerations  on device right_arm_no_hand returns  true or interface not availables 
[[ERROR]CBW( /icubSim/left_leg ):  getMotorEncoders  on device left_leg returns  true or interface not availables 
ERROR][ERROR]CBW( /icubSim/left_leg ):  getMotorEncoderSpeeds  on device left_leg returns  true or interface not availables 
CBW( /icubSim/right_leg ):  getMotorEncoders  on device right_leg returns  true or interface not availables 
[ERROR[ERROR]CBW( /icubSim/right_leg ):  getMotorEncoderSpeeds  on device right_leg returns  true or interface not availables 
]CBW( /icubSim/left_leg ):  getMotorEncoderAccelerations  on device left_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/right_leg ):  getMotorEncoderAccelerations  on device right_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_leg ):  getMotorEncoders  on device left_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_leg ):  getMotorEncoderSpeeds  on device left_leg returns  true or interface not availables 
[ERROR]CBW( /icubSim/left_leg ):  getMotorEncoderAccelerations  on device left_leg returns  true or interface not availables 
```

**Comment by traversaro** [comment] 2018-05-17 16:14
I think this is related to https://github.com/robotology/yarp/pull/1668 .

**Comment by DanielePucci** [comment] 2018-05-17 16:39
Probably @diegoferigo can take over on this?

**Comment by traversaro** [comment] 2018-05-17 16:55
cc @valegagge

**Comment by valegagge** [comment] 2018-05-18 12:48
This issue is not a bug, but only an annoying prints...and more over not so clear! :(

The issue is due that now controlBoardWrapper prints an error if the device doen't implement the interface  to which the called function belongs. (in our case IMotorEncoder::getEncoders)
Infact the motion control device of Gazebo doesn't implement IMotorEcnoder interface and ControlBoardWrapper calls IMotorEncoder->getEncoders in the run method in order to publish motor ecoder values on stateExt port.

However In order to mantain the old behaviour I'll remove this prints.

**Comment by valegagge** [comment] 2018-05-18 13:16
see https://github.com/robotology/yarp/commit/0c0de4a9331b9b843ac4b3d3746c074dd0427249

**Comment by traversaro** [comment] 2018-08-23 20:26
Fixed by https://github.com/robotology/yarp/commit/0c0de4a9331b9b843ac4b3d3746c074dd0427249 , closing.

**Closed by traversaro** 2018-08-23 20:26 UTC
